apiVersion: apps/v1
kind: Deployment
metadata:
  name: neptune-deployment
spec:
  selector:
    matchLabels:
      app: neptune
  replicas: 6
  template:
    metadata:
      labels:
        app: neptune
    spec:
      containers:
        - name: neptune
          image: neptuneacr.azurecr.io/neptune:1.0
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: neptune-secret
                  key: secret_key_base
            - name: PORT
              value: "4000"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: neptune-secret
                  key: database_url
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
